//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LackedMagazines.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LackedMagazines.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;Expected issue numbers&lt;/th&gt;.
        /// </summary>
        internal static string ExpectedIssueNumbers {
            get {
                return ResourceManager.GetString("ExpectedIssueNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Haven&apos;t orders.
        /// </summary>
        internal static string HaventOrders {
            get {
                return ResourceManager.GetString("HaventOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration of periodical receipts for the period`:.
        /// </summary>
        internal static string MagazineRegistrationForPeriod {
            get {
                return ResourceManager.GetString("MagazineRegistrationForPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;Magazine or newspaper title&lt;/th&gt;.
        /// </summary>
        internal static string MagazineTitle {
            get {
                return ResourceManager.GetString("MagazineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;Missed issues&lt;/th&gt;.
        /// </summary>
        internal static string MissedIssues {
            get {
                return ResourceManager.GetString("MissedIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Missing: {0}.
        /// </summary>
        internal static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   No order info for {0}.
        /// </summary>
        internal static string NoOrderInfoFor {
            get {
                return ResourceManager.GetString("NoOrderInfoFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Present: {0}.
        /// </summary>
        internal static string Present {
            get {
                return ResourceManager.GetString("Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;th&gt;Registered issues&lt;/th&gt;.
        /// </summary>
        internal static string RegisteredIssues {
            get {
                return ResourceManager.GetString("RegisteredIssues", resourceCulture);
            }
        }
    }
}
