#if FW45

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from NumberRanges.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace AM.Text.Ranges {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="NumberRangesParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface INumberRangesListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="NumberRangesParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] NumberRangesParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NumberRangesParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] NumberRangesParser.RangeContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="NumberRangesParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] NumberRangesParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NumberRangesParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] NumberRangesParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="NumberRangesParser.one"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOne([NotNull] NumberRangesParser.OneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NumberRangesParser.one"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOne([NotNull] NumberRangesParser.OneContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="NumberRangesParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] NumberRangesParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="NumberRangesParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] NumberRangesParser.ItemContext context);
}
} // namespace AM.Text.Ranges

#endif