//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LitresTicket.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LitresTicket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В БД уже есть привязка к ЛИТРЕС. Перезаписать?.
        /// </summary>
        internal static string MainForm_AlreadyBinded {
            get {
                return ResourceManager.GetString("MainForm_AlreadyBinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо задать логин И пароль.
        /// </summary>
        internal static string MainForm_BothLoginAndPasswordRequired {
            get {
                return ResourceManager.GetString("MainForm_BothLoginAndPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные успешно записаны в БД.
        /// </summary>
        internal static string MainForm_DataWasCommited {
            get {
                return ResourceManager.GetString("MainForm_DataWasCommited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка в e-mail!.
        /// </summary>
        internal static string MainForm_EmailError {
            get {
                return ResourceManager.GetString("MainForm_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Литрес.
        /// </summary>
        internal static string MainForm_Litres {
            get {
                return ResourceManager.GetString("MainForm_Litres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено несколько читателей с указанным билетом.
        /// </summary>
        internal static string MainForm_ManyReadersFound {
            get {
                return ResourceManager.GetString("MainForm_ManyReadersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не введен билет ИОГУНБ.
        /// </summary>
        internal static string MainForm_NoIogunbTicket {
            get {
                return ResourceManager.GetString("MainForm_NoIogunbTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не найден читатель с указанным билетом.
        /// </summary>
        internal static string MainForm_NoReaderFound {
            get {
                return ResourceManager.GetString("MainForm_NoReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не заданы логин и пароль. Нечего привязывать!.
        /// </summary>
        internal static string MainForm_NothingToDo {
            get {
                return ResourceManager.GetString("MainForm_NothingToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Привязка ЛИТРЕС.
        /// </summary>
        internal static string MainForm_QuestionTitle {
            get {
                return ResourceManager.GetString("MainForm_QuestionTitle", resourceCulture);
            }
        }
    }
}
