//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IrbisSearchQuery.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

// Ambiguous reference in cref attribute
#pragma warning disable 0419

// XML comment has cref attribute that could not be resolved
#pragma warning disable 1574

namespace ManagedIrbis.Search {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIrbisSearchQueryListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public partial class IrbisSearchQueryBaseListener : IIrbisSearchQueryListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStarOperator2([NotNull] IrbisSearchQueryParser.StarOperator2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStarOperator2([NotNull] IrbisSearchQueryParser.StarOperator2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStarOperator3([NotNull] IrbisSearchQueryParser.StarOperator3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStarOperator3([NotNull] IrbisSearchQueryParser.StarOperator3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStarOperator1([NotNull] IrbisSearchQueryParser.StarOperator1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.starOperator1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStarOperator1([NotNull] IrbisSearchQueryParser.StarOperator1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlusOperator3([NotNull] IrbisSearchQueryParser.PlusOperator3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlusOperator3([NotNull] IrbisSearchQueryParser.PlusOperator3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlusOperator2([NotNull] IrbisSearchQueryParser.PlusOperator2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlusOperator2([NotNull] IrbisSearchQueryParser.PlusOperator2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.fOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFOperator([NotNull] IrbisSearchQueryParser.FOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.fOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFOperator([NotNull] IrbisSearchQueryParser.FOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.parenOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenOuter([NotNull] IrbisSearchQueryParser.ParenOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.parenOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenOuter([NotNull] IrbisSearchQueryParser.ParenOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.gOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGOperator([NotNull] IrbisSearchQueryParser.GOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.gOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGOperator([NotNull] IrbisSearchQueryParser.GOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlusOperator1([NotNull] IrbisSearchQueryParser.PlusOperator1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.plusOperator1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlusOperator1([NotNull] IrbisSearchQueryParser.PlusOperator1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReference([NotNull] IrbisSearchQueryParser.ReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReference([NotNull] IrbisSearchQueryParser.ReferenceContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] IrbisSearchQueryParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] IrbisSearchQueryParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.entry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntry([NotNull] IrbisSearchQueryParser.EntryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.entry"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntry([NotNull] IrbisSearchQueryParser.EntryContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.levelTwoOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelTwoOuter([NotNull] IrbisSearchQueryParser.LevelTwoOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.levelTwoOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelTwoOuter([NotNull] IrbisSearchQueryParser.LevelTwoOuterContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.dotOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotOperator([NotNull] IrbisSearchQueryParser.DotOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.dotOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotOperator([NotNull] IrbisSearchQueryParser.DotOperatorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="IrbisSearchQueryParser.levelOneOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevelOneOuter([NotNull] IrbisSearchQueryParser.LevelOneOuterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IrbisSearchQueryParser.levelOneOuter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevelOneOuter([NotNull] IrbisSearchQueryParser.LevelOneOuterContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace ManagedClient.Search
