// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

/* PftBreakException.cs -- generated by break statement
 * Ars Magna project, http://arsmagna.ru
 * -------------------------------------------------------
 * Status: poor
 */

#region Using directives

using System;

using CodeJam;

using JetBrains.Annotations;

#endregion

namespace ManagedIrbis.Pft.Infrastructure
{
    /// <summary>
    /// Generated by 'break' statement.
    /// </summary>
    sealed class PftBreakException
        : Exception
    {
        #region Properties

        /// <summary>
        /// Node generated the exception.
        /// </summary>
        [NotNull]
        public PftNode Node { get; private set; }

        #endregion

        #region Construction

        /// <summary>
        /// Constructor.
        /// </summary>
        public PftBreakException
            (
                [NotNull] PftNode node
            )
        {
            Code.NotNull(node, "node");

            Node = node;
        }

        #endregion
    }
}
