// This is an open source non-commercial project. Dear PVS-Studio, please check it.
// PVS-Studio Static Code Analyzer for C, C++ and C#: http://www.viva64.com

/* PftExitException.cs -- generated by break statement
 * Ars Magna project, http://arsmagna.ru
 * -------------------------------------------------------
 * Status: poor
 */

#region Using directives

using System;

using CodeJam;

using JetBrains.Annotations;

#endregion

namespace ManagedIrbis.Pft.Infrastructure
{
    /// <summary>
    /// Generated by debugger.
    /// </summary>
    sealed class PftExitException
        : Exception
    {
        #region Properties

        #endregion

        #region Construction

        #endregion
    }
}
